### ISSUE TITLE
ClassCastException in InstanceCache.getForTypeClass for gobject.ParamSpec$ParamSpecImpl

### ISSUE THREAD

**Issue by JFronny** [jwharm/java-gi#66]
I was playing around with my GTK app when I came across this.
It is definitely possible that this exception is due to a mistake I made, but I don't see what specifically would have caused it.

```
java.lang.ClassCastException: class org.gnome.gobject.ParamSpec$ParamSpecImpl cannot be cast to class org.gnome.gobject.GObject (org.gnome.gobject.ParamSpec$ParamSpecImpl and org.gnome.gobject.GObject are in unnamed module of loader 'app')
	at io.github.jwharm.javagi.interop.InstanceCache.getForTypeClass(InstanceCache.java:107)
	at org.gnome.gobject.TypeInstance.readGClass(TypeInstance.java:67)
	at io.github.jwharm.javagi.interop.TypeCache.getConstructor(TypeCache.java:37)
	at io.github.jwharm.javagi.interop.InstanceCache.getForType(InstanceCache.java:58)
	at org.gnome.gobject.GObject$Notify.upcall(GObject.java:1677)
	at org.gnome.gio.Application.run(Application.java:1024)
	at io.gitlab.jfronny.inceptum.gtk.GtkMain.setupApplication(GtkMain.kt:61)
	at io.gitlab.jfronny.inceptum.gtk.GtkMain.showGui(GtkMain.kt:36)
	at io.gitlab.jfronny.inceptum.gtk.GtkMain.main(GtkMain.kt:26)
```

**Comment by jwharm** [comment]
This is a bug, thanks for reporting.

I tried to fix it, can you please retest with a build from the main branch?

**Comment by jwharm** [comment]
Seeing as you're using Kotlin, and java-gi requires JDK 20, further testing will have to wait until Kotlin releases support for JDK 20. Target version is [1.9.0](https://youtrack.jetbrains.com/issue/KT-57495/Add-JVM-target-bytecode-version-20).

**Comment by JFronny** [comment]
I am currently experiencing an issue unrelated to this, so I can't properly confirm whether this is fixed. It's probably best to assume it is and reopen the issue if it comes up again.
