### ISSUE TITLE
setText on Entry causes  IndexOutOfBoundsException

### ISSUE THREAD

**Issue by MMarco94** [jwharm/java-gi#72]
Hello, thanks for the amazing work!

I found an issue with the  gtk widget `Entry`: setting the text while `onInsertText` is registered causes an `IndexOutOfBoundsException`.

To reproduce:
```kotlin
Entry.builder().build().apply {
    onInsertText { text, length, position -> println("On insert $text") }
    text = "asdasduhv"
}
```

the error I get is:
```
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ array: Optional.empty address:140381219967908 limit: 0 }; new offset = 0; new length = 4
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.outOfBoundException(AbstractMemorySegmentImpl.java:371)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:357)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:70)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:124)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:448)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkBounds(AbstractMemorySegmentImpl.java:346)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkAccess(AbstractMemorySegmentImpl.java:311)
	at java.base/java.lang.invoke.VarHandleSegmentAsInts.checkAddress(VarHandleSegmentAsInts.java:81)
	at java.base/java.lang.invoke.VarHandleSegmentAsInts.get(VarHandleSegmentAsInts.java:108)
	at java.base/java.lang.foreign.MemorySegment.get(MemorySegment.java:1552)
	at org.gnome.gtk.Editable$InsertText.upcall(Editable.java:1022)
	at org.gnome.gtk.Editable.setText(Editable.java:745)
	at HelloWorldKt.activate(HelloWorld.kt:41)
	at HelloWorldKt.main$lambda$0(HelloWorld.kt:10)
	at org.gnome.gio.Application$Activate.upcall(Application.java:1557)
	at org.gnome.gio.Application.run(Application.java:1123)
	at HelloWorldKt.main(HelloWorld.kt:11)
	at HelloWorldKt.main(HelloWorld.kt)
```

**Comment by jwharm** [comment]
Thanks for the issue report.

These `IndexOutOfBoundsExceptions` are thrown since JDK 20 introduced strict bounds checks on memory segments returned by foreign functions. This requires explicit "reinterpretation" from an empty segment to the correct size. Apparently I forgot to do this in case of an upcall from native code into a Java callback, with an out-parameter (the `position` in your case).

It's a rather ugly bug, so when the fix is ready, I will publish a minor release (0.7.2) for it.

**Comment by MMarco94** [comment]
Amazing, I confirm it works in `0.7.2`, thanks!

**Comment by jwharm** [comment]
Nice!
Let me know if you find other issues, or have ideas for improvements.
