### ISSUE TITLE
Creating nested value types seem to not work?

### ISSUE THREAD

**Issue by pontaoski** [jwharm/java-gi#87]
The `Point` and the `Size` here initialise just fine, but the `Rect` doesn't seem to be happy.
```scala
val rect = Rect.allocate(arena, Point.allocate(arena, 0, 0), Size.allocate(arena, 16, 16))
```
```
[error] java.lang.IllegalArgumentException: Path does not select a value layout
[error]         at java.base/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:199)
[error]         at java.base/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:194)
[error]         at java.base/java.lang.foreign.MemoryLayout.computePathOp(MemoryLayout.java:486)
[error]         at java.base/java.lang.foreign.MemoryLayout.varHandle(MemoryLayout.java:419)
[error]         at org.gnome.graphene.Rect.writeOrigin(Rect.java:131)
[error]         at org.gnome.graphene.Rect.allocate(Rect.java:109)
[error]         at Shades.ExampleWidget$.<clinit>(ExampleWidget.scala:21)
```

**Comment by jwharm** [comment]
You're right, this is a bug. The generated memory layout is correct, but the `read`/`write` methods are broken.
