### ISSUE TITLE
Suppressed: java.lang.UnsatisfiedLinkError: no libgobject-2.0.so.0 in java.library.path: 

### ISSUE THREAD

**Issue by akashKarmakar02** [jwharm/java-gi#94]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.gnome.gobject.TypeInstance.<clinit>(TypeInstance.java:43)
	at org.example.Main.<init>(Main.java:15)
	at org.example.Main.main(Main.java:9)
Caused by: io.github.jwharm.javagi.interop.InteropException: Could not load library libgobject-2.0.so.0
	at io.github.jwharm.javagi.interop.LibLoad.loadLibrary(LibLoad.java:50)
	at org.gnome.gobject.GObjects.<clinit>(GObjects.java:149)
	... 3 more
	Suppressed: java.lang.UnsatisfiedLinkError: no libgobject-2.0.so.0 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
		at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
		at java.base/java.lang.System.loadLibrary(System.java:2063)
		at io.github.jwharm.javagi.interop.LibLoad.loadLibrary(LibLoad.java:54)
		... 4 more

**Comment by jwharm** [comment]
Thanks for trying out java-gi!

The exception occured because the native libraries cannot be found in the default locations. 

If you're on a Debian/Ubuntu-derived distribution, it's `/lib/x86_64-linux-gnu`. You can set it with the command line parameter `-Djava.library.path=/lib/...` or, if you use Gradle, check out [this example](https://github.com/jwharm/java-gi-examples/blob/main/HelloWorld/build.gradle#L26).
